version: '3.8'
services:
    hotel-app:
        container_name: hotel-app
        build:
            context: ./src
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html/
        ports:
            - 9905:80
        env_file:
            - .env
        networks:
            - hotel_app
    hotel-db:
        container_name: hotel-db
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "9906:3306"
        volumes:
            - ./src/database:/docker-entrypoint-initdb.d
            - hoteldbdata:/var/lib/mysql
        networks:
            - hotel_app
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '9907:80'
        restart: always
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_PORT: ${PMA_PORT}
        networks:
            - hotel_app
    
networks:
  hotel_app:
    driver: bridge

volumes:
  hoteldbdata: